<a href="https://colab.research.google.com/github/souled23/helloworld/blob/main/Python_Numpy_refresher.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Tutorial**

Numpy Constructors

In [1]:
import numpy as np

In [3]:
a=np.array([1,3,4,6,8])
print(a)

[1 3 4 6 8]


In [5]:
a=np.arange(1,12,2) 
#start,stop,step
print(a)

[ 1  3  5  7  9 11]


In [7]:
a=np.linspace(1,2,13)
#start,stop,no of items
print(a)

[1.         1.08333333 1.16666667 1.25       1.33333333 1.41666667
 1.5        1.58333333 1.66666667 1.75       1.83333333 1.91666667
 2.        ]


In [11]:
A=np.zeros((4,2))
print(A)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [15]:
A=np.ones((2,3),dtype=np.int16)
print(A)

[[1 1 1]
 [1 1 1]]


In [17]:
A=np.full((6,),88)
print(A)

[88 88 88 88 88 88]


In [21]:
A=np.fromstring('2 3 4 5', dtype=np.int, sep=' ')
print(A)

[2 3 4 5]


In [23]:
A=np.array([[1,2,3],[3,5,6]])
print(A)

[[1 2 3]
 [3 5 6]]


In [24]:
b=np.zeros_like(A)
print(b)

[[0 0 0]
 [0 0 0]]


Numpy Attributes

In [25]:
print(A.size)
print(A.shape)
print(A.ndim)
print(A.itemsize)
print(A.dtype)
print(A.nbytes) # a.size*a.itemsize


6
(2, 3)
2
8
int64
48


Indexing and Slicing

In [29]:
print(A)
print(A[1])
print(A[0,2])
print(A[:1])
print(A[1:2,2:1]) #[start:stop:step,start:stop:step]

[[1 2 3]
 [3 5 6]]
[3 5 6]
3
[[1 2 3]]
[]


In [38]:
b=np.arange(-9,-3,).reshape(2,3)
print(b)
c=b.swapaxes(0,1)
print(c)
d=c.flatten()
print(d)

[[-9 -8 -7]
 [-6 -5 -4]]
[[-9 -6]
 [-8 -5]
 [-7 -4]]
[-9 -6 -8 -5 -7 -4]


Numpy Datatypes

In [39]:
import pprint as pp
pp.pprint(np.sctypes)

{'complex': [<class 'numpy.complex64'>,
             <class 'numpy.complex128'>,
             <class 'numpy.complex256'>],
 'float': [<class 'numpy.float16'>,
           <class 'numpy.float32'>,
           <class 'numpy.float64'>,
           <class 'numpy.float128'>],
 'int': [<class 'numpy.int8'>,
         <class 'numpy.int16'>,
         <class 'numpy.int32'>,
         <class 'numpy.int64'>],
 'others': [<class 'bool'>,
            <class 'object'>,
            <class 'bytes'>,
            <class 'str'>,
            <class 'numpy.void'>],
 'uint': [<class 'numpy.uint8'>,
          <class 'numpy.uint16'>,
          <class 'numpy.uint32'>,
          <class 'numpy.uint64'>]}


Readiing and Writing using  Numpy

In [ ]:
f=np.loadtxt('data.txt',skiprows=1 ,delimiter=',' ,dtype=int.32)
np.savetxt('dtaa2.txt',f,delimiter=',' ,dtype=int.32,header='a;b;c;d;e;f;g' ,comments='')

In [ ]:
np.genfromtxt(data.txt',skiprows=1 ,delimiter=',' ,dtype=int.32)

Mathematical Functions

In [44]:
g=np.arange(1,5,1).reshape(2,2)
print(g)

[[1 2]
 [3 4]]


In [45]:
print(g>4)

[[False False]
 [False False]]


In [48]:
print(g.min())
print(g.max())
print(g.var())
print(g.std())
print(g.mean())
print(g.sum(axis=1))
print(g.argmin())
print(g.argmax())

1
4
1.25
1.118033988749895
2.5
[3 7]
0
3
